class org.apache.commons.lang3.exception.ExceptionUtilsTest$ExceptionWithCause extends java.lang.Exception
{
    private java.lang.Throwable cause;

    public void <init>(java.lang.String, java.lang.Throwable)
    {
        java.lang.Throwable cause;
        org.apache.commons.lang3.exception.ExceptionUtilsTest$ExceptionWithCause this;
        java.lang.String str;

        this := @this: org.apache.commons.lang3.exception.ExceptionUtilsTest$ExceptionWithCause;

        str := @parameter0: java.lang.String;

        cause := @parameter1: java.lang.Throwable;

        specialinvoke this.<java.lang.Exception: void <init>(java.lang.String)>(str);

        virtualinvoke this.<org.apache.commons.lang3.exception.ExceptionUtilsTest$ExceptionWithCause: void setCause(java.lang.Throwable)>(cause);

        return;
    }

    public void <init>(java.lang.Throwable)
    {
        java.lang.Throwable cause;
        org.apache.commons.lang3.exception.ExceptionUtilsTest$ExceptionWithCause this;

        this := @this: org.apache.commons.lang3.exception.ExceptionUtilsTest$ExceptionWithCause;

        cause := @parameter0: java.lang.Throwable;

        specialinvoke this.<java.lang.Exception: void <init>()>();

        virtualinvoke this.<org.apache.commons.lang3.exception.ExceptionUtilsTest$ExceptionWithCause: void setCause(java.lang.Throwable)>(cause);

        return;
    }

    public java.lang.Throwable getCause()
    {
        java.lang.Throwable $stack1;
        org.apache.commons.lang3.exception.ExceptionUtilsTest$ExceptionWithCause this;

        this := @this: org.apache.commons.lang3.exception.ExceptionUtilsTest$ExceptionWithCause;

        $stack1 = this.<org.apache.commons.lang3.exception.ExceptionUtilsTest$ExceptionWithCause: java.lang.Throwable cause>;

        return $stack1;
    }

    public void setCause(java.lang.Throwable)
    {
        java.lang.Throwable cause;
        org.apache.commons.lang3.exception.ExceptionUtilsTest$ExceptionWithCause this;

        this := @this: org.apache.commons.lang3.exception.ExceptionUtilsTest$ExceptionWithCause;

        cause := @parameter0: java.lang.Throwable;

        this.<org.apache.commons.lang3.exception.ExceptionUtilsTest$ExceptionWithCause: java.lang.Throwable cause> = cause;

        return;
    }
}
